all:
  hosts:
    master:
      ansible_host: 51.250.5.253
      ip: 10.10.1.5
      access_ip: 10.10.1.5
      ansible_user: ubuntu
    node1:
      ansible_host: 158.160.86.120
      ip: 10.10.2.12
      access_ip: 10.10.2.12
      ansible_user: ubuntu
    node2:
      ansible_host: 130.193.44.232
      ip: 10.10.3.11
      access_ip: 10.10.3.11
      ansible_user: ubuntu
  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        master:
        node1:
        node2:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
